name: Build, Publish Docker Image and run docker image on remote server

on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      working-directory: ./security-server/
      run: mvn clean compile install
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       repository: exceptiongenerator/send-anywhere-microservice
       tags: latest
    
    - name: Executing commands on remote server
      uses: ExceptionGenerator/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        command: |
            cd /home/shiv-projects/transfer-service &&
            docker stop send-app &&
            docker rm -f send-app &&
            docker pull exceptiongenerator/send-anywhere-microservice &&
            docker run --name send-app -v /home/shiv-projects/transfer-service:/home/shiv-projects/transfer-service -it -p 8090:8090 -d exceptiongenerator/send-anywhere-microservice &&
            docker logs send-app
