name: Execute running command on cloude server
on: 
  push: 
    branches: [dev]
jobs:
  build:
    name: Deploye
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        command: |
            cd /home/shiv-projects/transfer-service &&
            docker stop send-app &&
            docker rm -f send-app &&
            docker pull exceptiongenerator/send-anywhere-microservice &&
            docker run --name send-app -v /home/shiv-projects/transfer-service:/home/shiv-projects/transfer-service -it -p 8090:8090 -d exceptiongenerator/send-anywhere-microservice &&
            docker logs send-app &
