name: Execute running command on cloude server
on: 
  push: 
    branches: [dev]
jobs:
  build:
    name: Deploye
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        command: |
            ls -l
